package com.example.skillshare.model

import kotlinx.serialization.Serializable

@Serializable
data class Skill(
    // ID is generated by the server, so it's not needed when creating a skill
    val id: String? = null,
    val title: String,
    val description: String,
    val duration: Int,
    val cost: Double,
    val location: String
)
